platform :ios, '9.0'
# require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'quakezone' do
  # Pods for quakezone
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/React'
  pod 'React-DevSupport', :path => '../node_modules/react-native/React'
  pod 'React-fishhook', :path => '../node_modules/react-native/Libraries/fishhook'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler/RNGestureHandler.podspec'

  # Flexbox Layout Manager Used By React Native
  # pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'

  # React Native
  # pod 'React', path: '../node_modules/react-native', subspecs: [
  #   # Comment out any unneeded subspecs to reduce bundle size.
  #   'Core',
  #   # 'DevSupport',
  #   # 'RCTActionSheet',
  #   # 'RCTAnimation',
  #   'RCTBlob',
  #   # 'RCTCameraRoll',
  #   # 'RCTGeolocation',
  #   # 'RCTImage',
  #   # 'RCTNetwork',
  #   # 'RCTPushNotification',
  #   # 'RCTSettings',
  #   # 'RCTTest',
  #   # 'RCTText',
  #   # 'RCTVibration',
  #   # 'RCTWebSocket',
  #   # 'RCTLinkingIOS'
  # ]

  # Mapbox
  pod 'react-native-mapbox-gl', :path => '../node_modules/@mapbox/react-native-mapbox-gl'


  pod 'RNSensors', :path => '../node_modules/react-native-sensors/RNSensors.podspec'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  target 'quakezoneTests' do
    inherit! :search_paths
    # Pods for testing
  end

  # use_native_modules!
end

target 'quakezone-tvOS' do
  # Pods for quakezone-tvOS

  target 'quakezone-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
